filter:
    excluded_paths:
        - micro/log/
        - micro/controllers/Autoloader.php
        - micro/controllers/admin/UbiquityMyAdminBaseController.php
        - tools/
        - project-files/
        - micro/addendum/
        - micro/annotations/
        - micro/js/Jquery.php
        - docs/
checks:
    php:
        code_rating: true
        duplication: true
