build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require twig/twig mindplay/annotations phpfastcache/phpfastcache monolog/monolog czproject/git-php phpmv/php-mv-ui
          - composer require codeception/codeception --dev
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      environment:
        php:
          version: 7.3
        hosts:
          'local.dev': '127.0.0.1'

        apache2:
          modules: ['rewrite']
          sites:
            ubiquity:
              web_root: 'tests/fw/'
              host: 'local.dev'
        selenium: true
      services:
          # For available tags, see https://hub.docker.com/_/mysql/
          mysql: 5.7
      tests:
        before:
          - mysql -u root mysql < tests/unit/db/messagerie.sql
          - (cd tests/fw && yes | ./../../vendor/bin/Ubiquity new prj-test-admin -b=messagerie -q=semantic -m -a)
          - composer -d=$(pwd)/tests/fw/prj-test-admin require codeception/c3 -dev
          - cp tests/fw/_index.php tests/fw/prj-test-admin/index.php
        override:
          - command: ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml
            coverage:
              file: tests/_output/coverage.xml
              format: clover

filter:
    excluded_paths:
        - Ubiquity/log/
        - Ubiquity/controllers/Autoloader.php
        - Ubiquity/controllers/admin/
        - Ubiquity/annotations/
        - Ubiquity/js/Jquery.php
        - Ubiquity/utils/git/UGitRepository.php
        - docs/
        - api/
        - documentation/
        - tests/
checks:
    php:
        code_rating: true
        duplication: true
