build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require twig/twig mindplay/annotations phpfastcache/phpfastcache monolog/monolog czproject/git-php phpmv/php-mv-ui
          - composer require codeception/codeception --dev
          - composer require phpmv/ubiquity-devtools:dev-master --dev
      environment:
        php:
          version: 7.2
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      dependencies:
        before:
#          - sudo apt-get install -y zip

      environment:
        php:
          version: 7.2
        hosts:
          dev.local: '127.0.0.1'
        apache2:
          modules: ['rewrite']
          sites:
            ubiquity:
              host: 'dev.local'
              web_root: 'src/'
        selenium: true
      services:
          # For available tags, see https://hub.docker.com/_/mysql/
          mysql: 5.7
      tests:
        before:
          - sudo cp src/tests/files/xdebug.ini /home/scrutinizer/.phpenv/versions/7.2.13/etc/conf.d/xdebug.ini
          - mysql -u root mysql < src/tests/unit/db/messagerie.sql
          - (yes | ./vendor/bin/Ubiquity new src -b=messagerie -q=semantic -m -a)
          - cp -f src/tests/files/composer.json src/composer.json
          - (cd src/ && composer update)
          - cp -f src/tests/files/_index.php src/index.php && cp -f src/tests/files/.htaccess src/.htaccess
          - sudo chmod 777 -R src/ && sudo chown -R www-data:www-data src/
          - sudo service apache2 restart && sudo service apache2 reload 
          - sudo curl -v http://dev.local/index.php?c=Admin

        override:
          - command: (cd src/ && ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml)
            coverage:
              file: src/tests/_output/coverage.xml
              format: clover
filter:
    paths: ["src/Ubiquity/*"]
    excluded_paths:
        - src/Ubiquity/log/
        - src/Ubiquity/controllers/Autoloader.php
        - src/Ubiquity/controllers/admin/
        - src/Ubiquity/annotations/
        - src/Ubiquity/js/Jquery.php
        - src/Ubiquity/utils/git/UGitRepository.php
checks:
    php:
        code_rating: true
        duplication: true
