build:
  nodes:
    my-tests:
      dependencies:
        before:
          - composer require twig/twig mindplay/annotations phpfastcache/phpfastcache monolog/monolog czproject/git-php phpmv/php-mv-ui
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
    excluded_paths:
        - Ubiquity/log/
        - Ubiquity/controllers/Autoloader.php
        - Ubiquity/controllers/admin/
        - Ubiquity/annotations/
        - Ubiquity/js/Jquery.php
        - Ubiquity/utils/git/UGitRepository.php
        - docs/
        - api/
        - documentation/
checks:
    php:
        code_rating: true
        duplication: true
