build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require twig/twig mindplay/annotations phpfastcache/phpfastcache monolog/monolog czproject/git-php phpmv/php-mv-ui
          - composer require codeception/codeception --dev
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: ./vendor/bin/codecept build && ./vendor/bin/codecept run unit --coverage-xml
            coverage:
              file: tests/_output/coverage.xml
              format: clover
filter:
    excluded_paths:
        - Ubiquity/log/
        - Ubiquity/controllers/Autoloader.php
        - Ubiquity/controllers/admin/
        - Ubiquity/annotations/
        - Ubiquity/js/Jquery.php
        - Ubiquity/utils/git/UGitRepository.php
        - docs/
        - api/
        - documentation/
        - tests/_support/
checks:
    php:
        code_rating: true
        duplication: true
