language: php

php:
  - 7.1
  - 7.2
  - 7.3
services:
  - mysql

branches:
  only:
    - master
before_install:
  - travis_retry composer selfupdate
  - composer require phpmv/ubiquity-devtools:dev-master --dev
  - "npm -g install npm@latest"
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
  - cp composer-tests.json composer.json
  - travis_retry composer install --no-interaction

  - mysql -u root mysql < src/tests/unit/db/messagerie.sql
  - (yes | ./vendor/bin/Ubiquity new src -b=messagerie -q=semantic -m -a)
  - cp -f src/tests/files/composer.json src/composer.json && cp -f src/tests/files/.htrouter.php src/.htrouter.php
  - cp -f src/tests/files/travis/acceptance.suite.yml src/tests/ && cp -f src/tests/files/travis/codeception.yml src/
  - (cd src/ && composer update -a)
  - cp -f src/tests/files/travis/_index.php src/index.php

before_script:
  - mkdir -p build/logs
  - "npm run selenium-install"
  - "npm run selenium-start &"
  - "sleep 5"
  - (cd src/ && php -S 127.0.0.1:8090 .htrouter.php &)
  - sleep 3

script:
  - (cd src/ && ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml)

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover src/tests/_output/coverage.xml